title: Cyrus Bhandari
logo: "/images/me.jpeg?raw=true"
description:
  <br>
  I bring a solid foundation in programming and problem-solving, ready to contribute to innovative projects. I am a quick learner with resourcefulness and
  a commitment to teamwork. With experience organizing national and university-level events, I have demonstrated the ability to handle responsibility and
  excel as a team player. Eager to adapt, learn, and stay current with industry trends, I look forward to joining a forward-thinking organization where
  my skills and enthusiasm can make a lasting impact.
  <br><br>
  B.Tech in Computer Science and Engineering with a CGPA of 8.9 at Kalinga Institute of Industrial Technology.
  <br><br>
  <a href="https://www.linkedin.com/in/cyrusbh//">View my LinkedIn Profile</a>

theme: jekyll-theme-minimal